// data.js
export const data = [
  {
    id: "frontend-developer",
    title: "Frontend Developer",
    employer: "Tech Company",
    departament: "It hardware / software",
    location: "Bucuresti, Romania",
    workingHours: "Cu norma intreaga / Partiala",
    jobType: "Telemunca / La birou / Hibrid",
    experience: "Experienta 0-3 ani / Internship / Practica",
    postedAt: "1 Aprilie 2023",
    salary: "4000 -  9000 Lei",
    jobDescription:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    responsabilities: [
      "Dezvoltarea interfeței utilizator.",
      "Colaborare cu echipa de design.",
      "Implementarea funcționalităților de front-end.",
    ],
    demands: [
      "Experiență în HTML, CSS, JavaScript.",
      "Cunoștințe de React sau Angular.",
      "Abilități bune de comunicare.",
    ],
    oferings: [
      "Salariu competitiv.",
      "Mediu de lucru dinamic.",
      "Oportunități de dezvoltare profesională.",
    ],
    generalInfo: [
      "Durata: nederminata",
      "Tipul de job: norma intreaga",
      "Experienta: senior, 4+ ani",
      "Locatia: 100% Remote",
    ],
    aboutEmployer: {
      photo: "linktophoto.com", // calea catre img
      name: "Laura Lavrici",
      title: "Recruter",
      phone: "0766 555 444",
      fax: "0766 555 444",
      email: "emailultau@yahoo.com",
      address: "Apahida, Strada pacii, nr 123",
    },
  },
  {
    id: "frontend-developer-2",
    title: "Frontend Developer",
    employer: "Tech Innovators",
    departament: "It hardware / software",
    location: "Iasi, Romania",
    workingHours: "Cu norma intreaga",
    jobType: "Telemunca / Hibrid",
    experience: "Experienta 1-2 ani",
    postedAt: "5 Martie 2023",
    salary: "4500 -  8500 Lei",
    jobDescription:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    responsabilities: [
      "Developing user interface components.",
      "Collaborating with designers.",
      "Implementing front-end functionalities.",
    ],
    demands: [
      "Experience in HTML, CSS, JavaScript.",
      "Knowledge of React or Angular.",
      "Good communication skills.",
    ],
    oferings: [
      "Competitive salary.",
      "Dynamic work environment.",
      "Professional development opportunities.",
    ],
    generalInfo: [
      "Durata: nedeterminata",
      "Tipul de job: norma intreaga",
      "Experienta: medie, 2-3 ani",
      "Locatia: 50% Remote",
    ],
    aboutEmployer: {
      photo: "./assets/details-assets/recruiter.png", // calea catre img
      name: "Ion Popescu",
      title: "HR Manager",
      phone: "0766 555 555",
      fax: "0766 555 556",
      email: "ion.popescu@techinnovators.ro",
      address: "Iasi, Strada Moldovei, nr 100",
    },
  },
  {
    id: "business-analyst",
    title: "Business Analyst",
    employer: "Business Solutions",
    departament: "Consultanta",
    location: "Cluj-Napoca, Cluj, Romania",
    workingHours: "Cu norma intreaga",
    jobType: "La birou",
    experience: "Experienta 3-5 ani",
    postedAt: "10 Aprilie 2023",
    salary: "5000 -  10000 Lei",
    jobDescription:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    responsabilities: [
      "Analiza cerințelor de business.",
      "Colaborare cu echipele tehnice.",
      "Elaborarea documentațiilor de specificații.",
    ],
    demands: [
      "Experiență în analiza de business.",
      "Cunoștințe în modelarea proceselor de business.",
      "Abilități de comunicare excelente.",
    ],
    oferings: [
      "Pachet salarial atractiv.",
      "Mediu de lucru profesional.",
      "Oportunități de avansare.",
    ],
    generalInfo: [
      "Durata: nedeterminata",
      "Tipul de job: norma intreaga",
      "Experienta: senior, 5+ ani",
      "Locatia: Cluj-Napoca",
    ],
    aboutEmployer: {
      photo: "./assets/details-assets/recruiter.png", // calea catre img
      name: "Maria Ionescu",
      title: "HR Specialist",
      phone: "0766 555 666",
      fax: "0766 555 667",
      email: "maria.ionescu@businesssolutions.ro",
      address: "Cluj-Napoca, Strada Libertatii, nr 10",
    },
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    employer: "Creative Designs",
    departament: "Design",
    location: "Timisoara, Romania",
    workingHours: "Cu norma intreaga",
    jobType: "La birou",
    experience: "Experienta 2-4 ani",
    postedAt: "15 Martie 2023",
    salary: "4000 -  7500 Lei",
    jobDescription:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    responsabilities: [
      "Crearea design-urilor UI/UX.",
      "Testarea interfețelor utilizator.",
      "Colaborare cu echipele de dezvoltare.",
    ],
    demands: [
      "Experiență în design UI/UX.",
      "Cunoștințe în utilizarea tool-urilor de design.",
      "Creativitate și atenție la detalii.",
    ],
    oferings: [
      "Salariu motivant.",
      "Mediu de lucru creativ.",
      "Proiecte interesante.",
    ],
    generalInfo: [
      "Durata: nedeterminata",
      "Tipul de job: norma intreaga",
      "Experienta: medie, 2-4 ani",
      "Locatia: Timisoara",
    ],
    aboutEmployer: {
      photo: "./assets/details-assets/recruiter.png", // calea catre img
      name: "Andreea Popa",
      title: "Lead Designer",
      phone: "0766 555 777",
      fax: "0766 555 778",
      email: "andreea.popa@creativedesigns.ro",
      address: "Timisoara, Strada Armoniei, nr 5",
    },
  },
  {
    id: "qa-tester",
    title: "QA Tester",
    employer: "Quality Assurance Ltd",
    departament: "QA",
    location: "Oradea, Romania",
    workingHours: "Cu norma intreaga",
    jobType: "Hibrid",
    experience: "Experienta 1-3 ani",
    postedAt: "20 Martie 2023",
    salary: "3500 -  7000 Lei",
    jobDescription:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    responsabilities: [
      "Testarea aplicațiilor software.",
      "Identificarea și raportarea bug-urilor.",
      "Colaborare cu echipele de dezvoltare.",
    ],
    demands: [
      "Experiență în testare software.",
      "Cunoștințe în utilizarea tool-urilor de testare.",
      "Abilități analitice bune.",
    ],
    oferings: [
      "Pachet salarial competitiv.",
      "Mediu de lucru dinamic.",
      "Oportunități de dezvoltare profesională.",
    ],
    generalInfo: [
      "Durata: nedeterminata",
      "Tipul de job: norma intreaga",
      "Experienta: junior, 1-3 ani",
      "Locatia: Oradea",
    ],
    aboutEmployer: {
      photo: "./assets/details-assets/recruiter.png", // calea catre img
      name: "Cristian Dobre",
      title: "QA Lead",
      phone: "0766 555 888",
      fax: "0766 555 889",
      email: "cristian.dobre@qaltd.ro",
      address: "Oradea, Strada Independentei, nr 15",
    },
  },
  {
    id: "scrum-master",
    title: "Scrum Master",
    employer: "Agile Solutions",
    departament: "Project Management",
    location: "Constanta, Romania",
    workingHours: "Cu norma intreaga",
    jobType: "Telemunca",
    experience: "Experienta 3-5 ani",
    postedAt: "25 Februarie 2023",
    salary: "6000 -  12000 Lei",
    jobDescription:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    responsabilities: [
      "Coordonarea echipelor agile.",
      "Facilitarea întâlnirilor scrum.",
      "Îmbunătățirea proceselor de lucru.",
    ],
    demands: [
      "Experiență ca Scrum Master.",
      "Certificare Scrum Master.",
      "Abilități excelente de comunicare.",
    ],
    oferings: [
      "Salariu competitiv.",
      "Mediu de lucru profesional.",
      "Oportunități de avansare.",
    ],
    generalInfo: [
      "Durata: nedeterminata",
      "Tipul de job: norma intreaga",
      "Experienta: senior, 3-5 ani",
      "Locatia: Telemunca",
    ],
    aboutEmployer: {
      photo: "./assets/details-assets/recruiter.png", // calea catre img
      name: "Elena Gheorghe",
      title: "Project Manager",
      phone: "0766 555 999",
      fax: "0766 555 990",
      email: "elena.gheorghe@agilesolutions.ro",
      address: "Constanta, Strada Marii, nr 20",
    },
  },
];
